name: Build and deploy container app to Azure Web App - devlin-master

on:
  push:
    branches:
      - alpha
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        # Use the login server name of your Azure Container Registry (e.g., myregistry.azurecr.io)
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Build and push container image to Azure Container Registry
    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        # Update the tags to point to your Azure Container Registry repository
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/fastapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'devlin-master'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8578fbeee0864aa18e7b608b7f276e96 }}
        # Update the image reference to use the Azure Container Registry repository
        images: '${{ secrets.ACR_LOGIN_SERVER }}/fastapi:${{ github.sha }}'
