# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - devlin-master

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://devlinduldulaocr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cbe2850344a245d187a111870dfe60a4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cdfbef1ad775463588ae8a3229f61297 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: devlinduldulaocr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cbe2850344a245d187a111870dfe60a4 }}/fastapi:${{ github.sha }}
        file: ./Dockerfile
        build-args: |
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          APP_CLIENT_ID=${{ secrets.APP_CLIENT_ID }}
          OPENAPI_CLIENT_ID=${{ secrets.OPENAPI_CLIENT_ID }}
          TENANT_ID=${{ secrets.TENANT_ID }}
          GRAPH_SECRET=${{ secrets.GRAPH_SECRET }}
          CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          AUTH_URL=https://login.microsoftonline.com/AUTH_URL
          CONFIG_URL=https://login.microsoftonline.com/CONFIG_URL
          TOKEN_URL= https://login.microsoftonline.com/TOKEN_URL
          DOMAIN=https://devlin-master.azurewebsites.net
          ENVIRONMENT=production
          BACKEND_CORS_ORIGINS=https://lemon-sea-0d997b303.5.azurestaticapps.net
          POSTGRES_SERVER=devlin-master.postgres.database.azure.com
          POSTGRES_PORT=5432
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'devlin-master'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2a5e0ca65cf1474da19d3052267f6038 }}
        images: 'devlinduldulaocr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cbe2850344a245d187a111870dfe60a4 }}/fastapi:${{ github.sha }}'